version: "3.9"

services:
  db:
    image: postgres
    container_name: db
    volumes:
      - data-emenu:/var/lib/postgresql/data
    ports:
      - 5432:5432
    env_file:
      - .env
  emenu:
    build:
      context: .
    container_name: emenu
    volumes:
      - ./app:/app
      - ./pyproject.toml:/app/pyproject.toml
    command: >
      bash -c "python manage.py migrate &&
               python manage.py runserver 0.0.0.0:8000"
    ports:
      - "8000:8000"
    tty: true
    restart: always
    env_file:
      - .env
    depends_on:
      - db

volumes:
  data-emenu:
