[tool.coverage.run]
branch = true
source = ["app"]

[tool.coverage.report]
show_missing = true
fail_under = 90

[tool.black]
line-length = 88
include = '\.pyi?$'
exclude = '''
/(
    \.git
  | \.hg
  | \.mypy_cache
  | \.tox
  | \.venv
  | _build
  | buck-out
  | build
  | dist
  | ^.*\b(migrations)\b.*$
)/
'''

[tool.isort]
profile = "black"
src_paths = ["app/**"]
force_alphabetical_sort_within_sections = true
skip_glob = [
  "**/venv/**",
  "**migrations**"
]

[tool.flake8]
exclude = "venv"
max-complexity = 10
max-line-length = 88
per-file-ignores = """
  settings.py:E501
  *migrations*:E501
  """

extend-ignore = """
    W503,
    E203,
    E701,
"""
# W503 - Line break occurred before a binary operator
# E203 - Whitespace before ':'
# E701 - Multiple statements on one line
