version: "3.9"

services:
  redis:
    image: redis:alpine
    container_name: redis
    ports:
      - 6379:6379

  db:
    image: postgres
    container_name: db
    volumes:
      - data-emenu:/var/lib/postgresql/data
    ports:
      - 5432:5432
    env_file:
      - .env

  emenu:
    build:
      context: .
    container_name: emenu
    entrypoint: scripts/app.sh
    volumes:
      - .:/app
    ports:
      - "8000:8000"
    tty: true
    restart: always
    env_file:
      - .env
    depends_on:
      - db

  celery:
    build:
      context: .
    container_name: celery
    restart: always
    entrypoint: scripts/worker.sh
    volumes:
      - .:/app
    env_file:
      - .env
    depends_on:
      - redis
      - emenu

volumes:
  data-emenu:
